<?php
	session_start();
	if (!isset($_SESSION['curr_uid'])){
		header("Location: ../index_.php?status=illegalattempt");
		exit();
	}
	else
		$uid = $_SESSION['curr_uid'];
?>
<!DOCTYPE html><html lang="en"><head><title>Give a Feedback | Heartfulness QRS</title><link rel="icon" type="image/png" href="../img/favicon.png"/><link rel="stylesheet" type="text/css" href="../css/styler.css"/><meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no"/><link rel="icon" type="image/png" href="../css/favicon.png"/><script type="text/javascript" src="../js/jquery-3.3.1.js"></script><meta charset="utf-8"/><script src="../jscodes/jquery-3.3.1.js"></script><style type="text/css">/*page-specific styles*//*h2 span{font-family: montserrat; font-weight: 350;}*/button{font-weight: 350;}.content-space{text-align: center;margin-bottom: 10%;}</style></head><body><div id="fluid-container"><header class="header">HEARTFULNESS</header><span class="__button__" style="font-size: 200%;"><a href="questions.php">&lt;&lt;&lt;</a></span><br/><div class="content-space"><h2 class="title">Leave a feedback.<br/><br/>It just takes a few minutes.<br/><span style="font-weight: lighter;font-size:60%;">Perhaps seconds.</span></h2></div><button id="btn1" class="button-btn">Your thoughts about the site</button><button id="btn2" class="button-btn">Suggestions</button><div id="part1"><form id="review" method="POST" action="process/fdbkchk.php?f=rev"><textarea name="ftext" rows="6" cols="40" placeholder="Your Review..." class="field text_area" REQUIRED></textarea><br/><input type="hidden" name="ftype" value="r"/><button type="submit" name="submit" class="__button__">Submit Review</button></form><p class="user-alert v-spacer"> Your review is private, and will be sent only to the webmaster.</p></div><div id="part2"><form id="suggestion" method="POST" action="process/fdbkchk.php?f=sugg"><textarea name="ftext" rows="6" cols="40" class="text_area field" placeholder="Suggest features, ideas or anything..." REQUIRED></textarea><br/><input type="hidden" name="ftype" value="s"/><button type="submit" name="submit" class="__button__">Suggest</button></form><p class="user-alert v-spacer"> Your suggestions are private, and will be sent only to the webmaster. </p></div></div></body></html><script type="text/javascript">$(document).ready(function(){$("#part1").hide();$("#part2").hide();var a=!1,b=!1;$("#btn1").click(function(){0==b?($("#part1").show(200),a=!0):1==b&&($("#part2").hide(200),b=!1,$("#part1").show(200),a=!0)});$("#btn2").click(function(){0==a?($("#part2").show(200),b=!0):1==a&&($("#part1").hide(200),a=!1,$("#part2").show(200),b=!0)})});</script>